title: Umberto Tarantino
logo: /assets/img/logo.png
show_downloads: false
description: ""
google_analytics:
theme: jekyll-theme-minimal

# Biographic information
avatar           : "profile.png"
name             : "Umberto Tarantino"
pronouns         : "he/they"  
bio              : "PhD student in Theoretical Computer Science @ IRIF"
location         : "Office 4060 <br>8 place Aurélie Nemours <br>75013 Paris"
employer         : "Université Paris Cité"
uri              : # URL
email            : "umberto.tarantino@irif.fr" 

# Academic websites
arxiv            : "https://arxiv.org/search/?searchtype=author&query=Tarantino%2C+U"
googlescholar    : # URL - Update with the correct link to your profile
researchgate     : "https://www.researchgate.net/profile/Umberto-Tarantino-3"
scopus           : # URL
  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
